// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxpkzqebqadcnipypigi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cGt6cWVicWFkY25pcHlwaWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTAzNDgsImV4cCI6MjA2MDg4NjM0OH0.SSU8oZCU9R05HJ0Br97k3w_r2t1hr5poB0Z4sONdJe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);